name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@vt


      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: install dependices
        run: npm install


      - name: run test
        run: npm test
